name: damage_proxy_maps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyproj  # Always include to avoid PROJ conflicts
  - jupyter
  - rasterio
  - fiona
  - geopandas
  - pip
  - gdal=3.8.3
  - pip:
    - sepal_ui==2.21.0
    - opensartoolkit
    - git+https://github.com/openforis/earthengine-api.git@v1.1.5rc0#egg=earthengine-api&subdirectory=python
